FROM openjdk:11

COPY target/money-plant-instrument-fetcher-0.0.1-SNAPSHOT.jar money-plant-instrument-fetcher-0.0.1-SNAPSHOT.jar
EXPOSE 8080

ENTRYPOINT ["java","-jar","money-plant-instrument-fetcher-0.0.1-SNAPSHOT.jar"]
